#!/bin/bash

set -eo pipefail

cd ios/ActionsPlayground

xcodebuild \
  -project ActionsPlayground.xcodeproj \
  -scheme ActionsPlayground \
  -destination platform=iOS\ Simulator,OS=16.4,name=iPhone\ 14 \
  clean build | xcpretty